formulas:
  quarto-prerelease:
    type: github
    repo: quarto-dev/quarto-cli
    file: Casks/quarto-prerelease.rb
    
  searchlink:
    type: github
    repo: ttscoff/searchlink
    file: Casks/searchlink.rb
    
  bookget:
    type: github
    repo: deweizhu/bookget
    file: Formula/bookget.rb

  font-xiaolai:
    type: github
    repo: lxgw/kose-font
    file: Casks/font-xiaolai.rb
    asset_name: Xiaolai-Regular.ttf
    
  font-xiaolai-mono:
    type: github
    repo: lxgw/kose-font
    file: Casks/font-xiaolai-mono.rb
    asset_name: XiaolaiMono-Regular.ttf
    
  maccalendar:
    type: github
    repo: bylinxx/MacCalendar
    file: Casks/maccalendar.rb
    asset_pattern: MacCalendar_.*\.dmg 
