name: Auto Update

on:
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write  # Allow writing to repo

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      
      - name: Install dependencies
        run: |
          gem install octokit
          gem install http
      
      - name: Run update script
        run: ruby .github/scripts/update-formulas.rb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 